### ISSUE TITLE
Configure Travis CI or similar, including PR checks

### ISSUE THREAD

**Issue by aaron-em** [firemacs/FiremacsWE#10]
A/C:
- When someone submits a PR, it triggers a CI build and surfaces the result on the PR page via Github build checks.

**Comment by Tapchicoma** [comment]
Optionally: [CircleCI](https://circleci.com/)

It is free to use for public repositories

**Comment by aaron-em** [comment]
@Tapchicoma I ended up going with Travis CI because I've already got other repos integrated with that and it was trivial to add this one too - see [.travis.yml there](https://github.com/aaron-em/firemacs-web-extension/blob/master/.travis.yml).

How would you compare Travis and Circle? I haven't tried Circle CI at all, and I'm curious how they stack up against one another.

**Comment by Tapchicoma** [comment]
@aaron-em for me main advantages of CirleCI:
- It uses docker images, so you can provide your own specific image for the project or use some public one
- Usually builds happen fast

You can check this documentation link for JS :https://circleci.com/docs/2.0/language-javascript/

And this link for example configuration: https://github.com/CircleCI-Public/circleci-demo-javascript-express/blob/master/.circleci/config.yml

**Comment by aaron-em** [comment]
Neat, thanks! Not necessarily applicable to this project - Travis is pretty snappy too, and Dockerizing this project would be a complexity increase of no tangible benefit, but I'll keep it in mind for possible future use.
