### ISSUE TITLE
Configure modern eslint

### ISSUE THREAD

**Issue by aaron-em** [firemacs/FiremacsWE#9]
A/C:
- When I write something bogus, the test suite rejects it and tells me what I did wrong.

Notes:
- Probably go with the Airbnb standard just out of general popularity. It's not perfect, but: it's good enough not to need a lot of complicated revising; it's well supported by eslint; it's easy to install; and it's a standard, which is a lot better than none.

**Comment by brudgers** [comment]
This is not the simplest thing that might work.
